config/routes.rb
Rails.application.routes.draw do
  resources :timezones
  get '/search/timezones' => 'timezones#search'

  root to: 'visitors#index'


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  scope '/admin' do
    resources :users, except: [:show, :edit]
  end
  get '/users/:id' => 'users#show', as: "show_user"
  get '/users/:id/edit' => 'users#edit', as: "edit_user"
  get '/search/users' => 'users#search'

  ##### API ROUTES #####

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end

    namespace :v1, as: nil do
      resources :timezones, except: [:new, :edit]
      get '/search/timezones' => 'timezones#search'

      resources :users, except: [:new, :edit]
      get '/search/users' => 'users#search'
    end
  end
end

app/models/timezone.rb
class Timezone < ActiveRecord::Base
  scope :starts_with, -> (name) { where("name like ?", "#{name}%")}

  include Filterable

  DATE_FORMAT = '%a, %d %b %Y %H:%M:%S'

  belongs_to :user
  validates_presence_of :name, :city, :user_id
  validates :difference, :inclusion => { :in => -12..12, :message => "must be between -12 and 12, inclusive" }, :presence => true

  # email of the user who created this timezone object, required for simple_form input
  attr_accessor :email

  def self.DATE_FORMAT
    DATE_FORMAT
  end

end

app/controllers/api/v1/timezones_controller.rb
class Api::V1::TimezonesController < Api::V1::ApiController
  before_action :authenticate_user!
  load_and_authorize_resource  # authorization
  respond_to :json

  def index
    @timezones, @local_times = current_user.get_timezones filtered_params
  end

  def show
  end

  def search
    @timezones, @local_times = current_user.get_timezones filtered_params
    render 'index', status: :ok
  end

  def create
    @timezone.user_id = current_user.id

    # attach the timezone to a different user if an admin requests so
    admin_attach_user_id

    if @timezone.save
      render status: :created
    else
      render json: @timezone.errors, status: :unprocessable_entity
    end
  end

  def update
    @timezone.user_id = current_user.id

    # attach the timezone to a different user if an admin requests so
    admin_attach_user_id

    if @timezone.update(timezone_params)
      render status: :ok
    else
      render json: @timezone.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @timezone
      @timezone.destroy
      render status: :ok
    else
      head :not_found
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def timezone_params
      params.require(:timezone).permit(:name, :city, :difference, :user_id, :email)
    end

    def filtered_params
      params.slice(:starts_with)
    end

    # attach the timezone to a different user if an admin requests so
    def admin_attach_user_id

      if current_user.admin?

        user_email = params[:timezone][:email] if params[:timezone][:email]
        if user_email
          user = User.find_by(email: user_email)
          @timezone.user_id = user.id if user
        else
          @timezone.user_id = current_user.id
        end

      end
    end
end

app/controllers/timezones_controller.rb
class TimezonesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource # authorization

  # GET /timezones
  def index
    @timezones, @local_times = current_user.get_timezones filtered_params
  end

  def search
    if request.xhr?
      @timezones, @local_times = current_user.get_timezones filtered_params
      render :text => render_to_string(:partial => 'timezone_table', layout: false), status: :ok
    else
      head :not_found
    end
  end

  # GET /timezones/1
  def show
    @local_time = Time.now.utc.advance(hours: @timezone.difference).strftime(Timezone.DATE_FORMAT)
  end

  # GET /timezones/new
  def new
  end

  # GET /timezones/1/edit
  def edit
  end

  # POST /timezones
  # POST /timezones.json
  def create
    @timezone.user_id = current_user.id

    # attach the timezone to a different user if an admin requests so
    admin_attach_user_id

    if @timezone.save
      redirect_via_turbolinks_to timezones_path, status: :created, notice: 'Timezone was successfully created.'
    else
      render json: render_to_string(:partial => 'form', layout: false), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /timezones/1
  # PATCH/PUT /timezones/1.json
  def update
    @timezone.user_id = current_user.id

    # attach the timezone to a different user if an admin requests so
    admin_attach_user_id

    respond_to do |format|
      if @timezone.update(timezone_params)
        format.html { redirect_via_turbolinks_to timezones_path, notice: 'Timezone was successfully updated.' }
        format.json { render :show, status: :ok, location: @timezone }
      else
        format.html { render json: render_to_string(:partial => 'form', layout: false), status: :unprocessable_entity }
        format.json { render json: @timezone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timezones/1
  # DELETE /timezones/1.json
  def destroy
    @timezone.destroy
    render json: @timezone
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def timezone_params
      params.require(:timezone).permit(:name, :city, :difference, :user_id, :email)
    end

    def filtered_params
      params.slice(:starts_with)
    end

    # attach the timezone to a different user if an admin requests so
    def admin_attach_user_id

      if current_user.admin?

        user_email = params[:timezone][:email] if params[:timezone][:email]
        if user_email
          user = User.find_by(email: user_email)
          @timezone.user_id = user.id if user
        else
          @timezone.user_id = current_user.id
        end

      end
    end


end

app/helpers/timezones_helper.rb
module TimezonesHelper
end

app/views/timezones/_form.html.erb
<%= simple_form_for @timezone, :remote => true do |f| %>
  <%= f.input :name %>
  <%= f.input :city %>
  <%= f.input :difference %>
  <% if current_user.admin? %>
    <%= f.input :email, hint: "Enter the email of the person you want to have this timezone attached to or leave blank so it attaches to yourself.", input_html: {value: @timezone.try(:user).try(:email) } %>
  <% end %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/timezones/_timezone_table.html.erb
<table id="timezone-table" class="table table-striped custab">

  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Time</th>
      <% if current_user.admin? %>
        <th>Owner</th>
        <th colspan="2"></th>
      <% else %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @timezones.each do |timezone| %>
      <tr id="timezone_<%= timezone.id %>">
        <td><%= link_to timezone.name, timezone %></td>
        <td><%= link_to timezone.city, timezone %></td>
        <td class="time"><strong><%= @local_times[timezone.id] %></strong></td>

        <% if current_user.admin? %>
          <td><%= timezone.user.email %></td>
        <% end %>

        <td><%= link_to 'Show', timezone %></td>
        <td><%= link_to 'Edit', edit_timezone_path(timezone) %></td>
        <td><%= link_to 'Destroy', timezone, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/timezones/edit.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>Editing timezone <%= @timezone.name %></h4>
      </div>

      <div class="panel-body">

        <div id="timezone_edit">
          <%= render 'form' %>
        </div>

        <p></p>
        <%= link_to 'Show', @timezone %> |
        <%= link_to 'Back', timezones_path %>
      </div>

    </div>
  </div>
</div>

app/views/timezones/index.html.erb
<div id="timezone-notice" class="alert alert-warning hidden">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <div id="flash_notice">
    Timezone was successfully deleted.
  </div>
</div>


<div class="container">
  <div class="row">
    <h3>Timezones</h3>
    <hr>
    
    <div class="column-lg-12">

      <%= simple_form_for :timezone, :method => 'get', :url => search_timezones_path, :html => { :id => 'timezone-search-form', :class => 'form-inline'}, :remote => true do |f| %>
        <%= f.label :name, 'Name', class: "filter-label" %>
        <%= f.input :starts_with, input_html: { name: 'starts_with', :value => params[:starts_with] }, label: false, :required => false %>
        <%= f.input :locale, :as => :hidden, :input_html => {:name => 'locale', :value => params[:locale] } %>
        <%= f.button :submit, t('search'), class: "btn btn-warning" %>
      <% end %>

      <div id="timezone-table-div">
        <%= render 'timezone_table' %>
      </div>


    </div>

  </div>

  <%= link_to 'New Timezone', new_timezone_path, class: "btn btn-primary" %>
</div>

app/views/timezones/new.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>New timezone</h4>
      </div>

      <div class="panel-body">

        <div id="timezone_create">
          <%= render 'form' %>
        </div>

        <p></p>
        <%= link_to 'Back', timezones_path %>
      </div>

    </div>
  </div>
</div>

app/views/timezones/show.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>Timezone <%= @timezone.name if @timezone.name %></h4>
      </div>

      <div class="panel-body">

        <p>
          <%= label_tag 'Name:' %>
          <%= @timezone.name %>
        </p>

        <p>
          <%= label_tag 'City:' %>
          <%= @timezone.city %>
        </p>


        <p>
          <%= label_tag 'Difference:' %>
          <%= @timezone.difference %>
        </p>

        <p>
          <%= label_tag 'Created by:' %>
          <%= @timezone.user.email %>
        </p>


        <p>
          <%= label_tag 'Local time:' %>
          <%= @local_time %>
        </p>

        <p></p>
        <%= link_to 'Edit', edit_timezone_path(@timezone) %> |
        <%= link_to 'Back', timezones_path %>
      </div>

    </div>
  </div>
</div>