config/routes.rb
Rails.application.routes.draw do
  resources :timezones
  get '/search/timezones' => 'timezones#search'

  root to: 'visitors#index'


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  scope '/admin' do
    resources :users, except: [:show, :edit]
  end
  get '/users/:id' => 'users#show', as: "show_user"
  get '/users/:id/edit' => 'users#edit', as: "edit_user"
  get '/search/users' => 'users#search'

  ##### API ROUTES #####

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end

    namespace :v1, as: nil do
      resources :timezones, except: [:new, :edit]
      get '/search/timezones' => 'timezones#search'

      resources :users, except: [:new, :edit]
      get '/search/users' => 'users#search'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include DeviseTokenAuth::Concerns::User
  include Filterable

  scope :starts_with, -> (name) { where("name like ?", "#{name}%")}

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :timezones, dependent: :destroy

  def get_timezones(filtered_params)

    if self.admin?
      @timezones = Timezone.filter filtered_params # admin can manage all timezones
    else
      @timezones = self.timezones.filter filtered_params # a user can only manage his own timezones
    end

    # convert to local times for each timezone
    @local_times = Hash.new
    @timezones.each do |zone|
      @local_times[zone.id] = Time.now.utc.advance(hours: zone.difference).strftime(Timezone.DATE_FORMAT)
    end

    return @timezones, @local_times
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  before_action :authenticate_user!
  load_and_authorize_resource # authorization
  respond_to :json

  def index
  end

  def search
    @users = User.filter filtered_params
    render 'index', status: :ok
  end

  def show
  end

  def create
    # puts params
    if @user.save
      render status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def update

    # password can be blank while updating
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      render status: :ok
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @user
      @user.destroy
      render status: :ok
    else
      head :not_found
    end
  end

  private

    def filtered_params
      params.slice(:starts_with)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if !current_user.nil? && current_user.admin?
        params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
      else
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
    end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_via_turbolinks_to timezones_path
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_via_turbolinks_to new_user_session_path
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      render json: render_to_string(:layout => false, :partial => 'users/registrations/form'), status: :unprocessable_entity
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource

    if resource.valid_password?(params[:user][:password])
      sign_in :user, resource
      set_flash_message(:notice, :signed_in)
      return redirect_via_turbolinks_to timezones_path
    end

    invalid_login_attempt
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out
    yield if block_given?
    return redirect_via_turbolinks_to root_path
  end

  protected

  def invalid_login_attempt
    set_flash_message(:alert, :invalid, :now => true)
    render json: render_to_string(:layout => false, :partial => 'layouts/messages'), status: :unauthorized
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource # authorization

  before_action :authenticate_user!

  def index
    puts @users
  end

  def search
    if request.xhr?
      @users = User.filter filtered_params
      render :text => render_to_string(:partial => 'user_table', layout: false), status: :ok
    else
      head :not_found
    end
  end

  def show
  end

  def new
    @minimum_password_length = (Devise.password_length).first # get the minimum length
  end

  def edit
  end

  def create
    if @user.save
      redirect_via_turbolinks_to users_path, status: :created, notice: 'User was successfully created.'
    else
      render json: render_to_string(:partial => 'form', layout: false), status: :unprocessable_entity
    end
  end

  def update

    # password can be blank while updating
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      sign_in @user, :bypass => true unless current_user.admin?
      redirect_via_turbolinks_to show_user_path(@user), status: :ok, notice: 'Updated!'
    else
      render json: render_to_string(:partial => 'form_edit', layout: false), status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    render json: @user
  end

  private

    def filtered_params
      params.slice(:starts_with)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if !current_user.nil? && current_user.admin?
        params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
      else
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, url: users_path, :remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true %>
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.input :admin %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= simple_form_for(@user, url: user_path, html: { method: :put }, :remote => true ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true %>
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
    <%= f.input :password_confirmation, required: false %>
    <% if current_user.admin? %>
      <%= f.input :admin %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, show_user_path(user) %></td>
<td><%= link_to user.email, show_user_path(user) %></td>
<% if user.admin? %>
  <td>yes</td>
<% else %>
  <td>no</td>
<% end %>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>

app/views/users/_user_table.html.erb
<table id="user-table" class="table table-striped custab">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr id="user_<%= user.id %>">
        <%= render user %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>Edit <%= @user.name %></h4>
      </div>

      <div class="panel-body">

        <div id="user_edit">
          <%= render 'form_edit' %>
        </div>

        <p></p>
        <%= link_to 'Back', :back %>
      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id="user-notice" class="alert alert-warning hidden">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <div id="flash_notice">
    User was successfully deleted.
  </div>
</div>


<div class="container">
  <div class="row">
    <h3>Users</h3>
    <hr>

    <div class="column-lg-12">

      <%= simple_form_for :user, :method => 'get', :url => search_users_path, :html => { :id => 'user-search-form', :class => 'form-inline'}, :remote => true do |f| %>
        <%= f.label :name, 'Name', class: "filter-label" %>
        <%= f.input :starts_with, input_html: { name: 'starts_with', :value => params[:starts_with] }, label: false, :required => false, class: "filter-label", autofocus: true %>
        <%= f.input :locale, :as => :hidden, :input_html => {:name => 'locale', :value => params[:locale] } %>
        <%= f.button :submit, t('search'), class: "btn btn-warning" %>
      <% end %>

      <div id="user-table-div">
          <%= render 'user_table' %>
      </div>

    </div>
  </div>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>New user</h4>
      </div>

      <div class="panel-body">

        <div id="user_create">
          <%= render 'form' %>
        </div>

        <p></p>
        <%= link_to 'Back', users_path %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="column-md-6">
    <div class="panel panel-info">

      <div class="panel-heading">
        <h4>User <%= @user.name if @user.name %></h4>
      </div>

      <div class="panel-body">

        <p>
          <%= label_tag 'Name:' %>
          <%= @user.name if @user.name %>
        </p>

        <p>
          <%= label_tag 'Email:' %>
          <%= @user.email if @user.email %>
        </p>

        <% if current_user.admin? %>
          <p>
            <%= label_tag 'Admin:' %>
            <%= @user.admin? %>
          </p>
        <% end %>

        <p></p>

        <%= link_to 'Edit', edit_user_path(@user) %>
        <% if current_user.admin? %>
          | <%= link_to 'Back', users_path %>
        <% end %>
      </div>

    </div>
  </div>
</div>