config/routes.rb
Rails.application.routes.draw do
  resources :timezones
  get '/search/timezones' => 'timezones#search'

  root to: 'visitors#index'


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  scope '/admin' do
    resources :users, except: [:show, :edit]
  end
  get '/users/:id' => 'users#show', as: "show_user"
  get '/users/:id/edit' => 'users#edit', as: "edit_user"
  get '/search/users' => 'users#search'

  ##### API ROUTES #####

  # token auth routes available at /api/v1/auth
  namespace :api, defaults: { format: :json } do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end

    namespace :v1, as: nil do
      resources :timezones, except: [:new, :edit]
      get '/search/timezones' => 'timezones#search'

      resources :users, except: [:new, :edit]
      get '/search/users' => 'users#search'
    end
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to "Profile", show_user_path(current_user), class: "nav navbar-nav" %></li>
  <li><%= link_to "Timezones", timezones_path, class: "nav navbar-nav" %></li>

  <% if current_user.admin? %>
    <li><%= link_to "Users", users_path, class: "nav navbar-nav" %></li>
  <% end %>

  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, remote: true, class: "nav navbar-nav" %></li>
<% else %>
  <li><%= link_to "Login", new_user_session_path, class: "nav navbar-nav" %></li>
  <li><%= link_to "Sign up", new_user_registration_path, class: "nav navbar-nav" %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timezoner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Timezoner" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">

     <div class="container">
       <div id="messages"></div>
       <%= render 'layouts/messages' %>
       
       <%= yield %>
     </div>

    </main>
  </body>
</html>